# Generated by Django 5.1.2 on 2024-11-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_characteristictype_remove_characteristic_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='CharacteristicType',
        ),
    ]
